[[unpaper]]
arch = "aarch64"
git-tree-sha1 = "46763e86c193ea0f3998ecabefea0872b3f1887e"
os = "macos"

    [[unpaper.download]]
    sha256 = "2e00b415183d833f2b6d654bb0717412bbde6e098f44a908f45c2b149ff2fd21"
    url = "https://github.com/JuliaBinaryWrappers/unpaper_jll.jl/releases/download/unpaper-v7.0.0+0/unpaper.v7.0.0.aarch64-apple-darwin.tar.gz"
[[unpaper]]
arch = "aarch64"
git-tree-sha1 = "a3b2e6c9f8dd4bff98c6f02b320013f2eeeb6bb2"
libc = "glibc"
os = "linux"

    [[unpaper.download]]
    sha256 = "39375974730b91b6a0749754758b1dafa1c6464962089094b9c5cfc98a31e460"
    url = "https://github.com/JuliaBinaryWrappers/unpaper_jll.jl/releases/download/unpaper-v7.0.0+0/unpaper.v7.0.0.aarch64-linux-gnu.tar.gz"
[[unpaper]]
arch = "aarch64"
git-tree-sha1 = "5d3a326cdd100ab468c4c4b41e7f071d9ada7af5"
libc = "musl"
os = "linux"

    [[unpaper.download]]
    sha256 = "d9988a162adfeec01b8013ce83ea1ac0b9af03bc0d165a97a76ca7aa8d1c1afc"
    url = "https://github.com/JuliaBinaryWrappers/unpaper_jll.jl/releases/download/unpaper-v7.0.0+0/unpaper.v7.0.0.aarch64-linux-musl.tar.gz"
[[unpaper]]
arch = "aarch64"
git-tree-sha1 = "bd17eda5e321e94f9dc807c424846c9217bcae80"
os = "freebsd"

    [[unpaper.download]]
    sha256 = "10b78f8c442b35fb25936da034b42bdae9ee369fdd7b713921f1e048ea7ba049"
    url = "https://github.com/JuliaBinaryWrappers/unpaper_jll.jl/releases/download/unpaper-v7.0.0+0/unpaper.v7.0.0.aarch64-unknown-freebsd.tar.gz"
[[unpaper]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a6c23b885f4ae07b1d40a2c1a2bc5cc8a9ced1fc"
libc = "glibc"
os = "linux"

    [[unpaper.download]]
    sha256 = "acf58b7dc3b8be5b7558490a00a2d00cbe6c3ee67406150afaa9144062987846"
    url = "https://github.com/JuliaBinaryWrappers/unpaper_jll.jl/releases/download/unpaper-v7.0.0+0/unpaper.v7.0.0.armv6l-linux-gnueabihf.tar.gz"
[[unpaper]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7fd36157dd166f6dbba9906cd93387c78a8a06f5"
libc = "musl"
os = "linux"

    [[unpaper.download]]
    sha256 = "656557fc6984e3cb1b14b51c3fe1da4016f744fb25094981c796514ff6a26f9a"
    url = "https://github.com/JuliaBinaryWrappers/unpaper_jll.jl/releases/download/unpaper-v7.0.0+0/unpaper.v7.0.0.armv6l-linux-musleabihf.tar.gz"
[[unpaper]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a4524a7d0f8689e7f22d1e6d4684495ded4caed2"
libc = "glibc"
os = "linux"

    [[unpaper.download]]
    sha256 = "4e33d4ffc149b4d7262e7ef86d3213f45f4b918352595859987bb2a62b61dec1"
    url = "https://github.com/JuliaBinaryWrappers/unpaper_jll.jl/releases/download/unpaper-v7.0.0+0/unpaper.v7.0.0.armv7l-linux-gnueabihf.tar.gz"
[[unpaper]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5f15cbbe559c678f70b77c56e95eaed6d150397b"
libc = "musl"
os = "linux"

    [[unpaper.download]]
    sha256 = "1633258affe84b00d107395363beba22086d49219c1fe13dc0334fea29bfe430"
    url = "https://github.com/JuliaBinaryWrappers/unpaper_jll.jl/releases/download/unpaper-v7.0.0+0/unpaper.v7.0.0.armv7l-linux-musleabihf.tar.gz"
[[unpaper]]
arch = "i686"
git-tree-sha1 = "2fa4d191ca5cf0489a9b96bde090ceb1535e66c3"
libc = "glibc"
os = "linux"

    [[unpaper.download]]
    sha256 = "cfee3c4977d40d73ad72c7e9387c99d803c9ad85a3806635bedd7f1dc758185f"
    url = "https://github.com/JuliaBinaryWrappers/unpaper_jll.jl/releases/download/unpaper-v7.0.0+0/unpaper.v7.0.0.i686-linux-gnu.tar.gz"
[[unpaper]]
arch = "i686"
git-tree-sha1 = "2c93f6332a42443149816d73bc148800afe072c0"
libc = "musl"
os = "linux"

    [[unpaper.download]]
    sha256 = "47ff2a270e629dbee7047ed042546e870c74230dc30366a48f544c340fedb807"
    url = "https://github.com/JuliaBinaryWrappers/unpaper_jll.jl/releases/download/unpaper-v7.0.0+0/unpaper.v7.0.0.i686-linux-musl.tar.gz"
[[unpaper]]
arch = "i686"
git-tree-sha1 = "7f57cddb1781050c0bc858e6d0d0b1a22c55f7e5"
os = "windows"

    [[unpaper.download]]
    sha256 = "27c5caa76203a5a8f5b9fc04e56bf4ed562d8c96df949181f37a7f531ecd351a"
    url = "https://github.com/JuliaBinaryWrappers/unpaper_jll.jl/releases/download/unpaper-v7.0.0+0/unpaper.v7.0.0.i686-w64-mingw32.tar.gz"
[[unpaper]]
arch = "powerpc64le"
git-tree-sha1 = "e15069ceaca9972d52be44bad68799918128097a"
libc = "glibc"
os = "linux"

    [[unpaper.download]]
    sha256 = "b4ef9eaf3aa0a961f846404040e66247c5af37c5f20da3a686df22a5aa63ed1f"
    url = "https://github.com/JuliaBinaryWrappers/unpaper_jll.jl/releases/download/unpaper-v7.0.0+0/unpaper.v7.0.0.powerpc64le-linux-gnu.tar.gz"
[[unpaper]]
arch = "riscv64"
git-tree-sha1 = "b070c571e4664c3d59c7d9c301a19d1a486ee14b"
libc = "glibc"
os = "linux"

    [[unpaper.download]]
    sha256 = "1c6a84a84cc8daa85ec6843dcdd75cc5bba5f93206dee28d78f7d37b387093f4"
    url = "https://github.com/JuliaBinaryWrappers/unpaper_jll.jl/releases/download/unpaper-v7.0.0+0/unpaper.v7.0.0.riscv64-linux-gnu.tar.gz"
[[unpaper]]
arch = "x86_64"
git-tree-sha1 = "ed69c5933f45d598b760c2a4ff34835f77cbbc97"
os = "macos"

    [[unpaper.download]]
    sha256 = "924e561dd39f374855e29e31526bc651fd219a36736cdc00c237ee8dbe53ab8f"
    url = "https://github.com/JuliaBinaryWrappers/unpaper_jll.jl/releases/download/unpaper-v7.0.0+0/unpaper.v7.0.0.x86_64-apple-darwin.tar.gz"
[[unpaper]]
arch = "x86_64"
git-tree-sha1 = "cfd6c652a6380736cc17d0255e64fd83ca1ec47a"
libc = "glibc"
os = "linux"

    [[unpaper.download]]
    sha256 = "e165d9937346b6e54b8d38b6229ab0f9123e99a36dbd8df652f992d3e5bdcfab"
    url = "https://github.com/JuliaBinaryWrappers/unpaper_jll.jl/releases/download/unpaper-v7.0.0+0/unpaper.v7.0.0.x86_64-linux-gnu.tar.gz"
[[unpaper]]
arch = "x86_64"
git-tree-sha1 = "8401c14883d489ee71c922aa8ba1d19d21834b53"
libc = "musl"
os = "linux"

    [[unpaper.download]]
    sha256 = "24847c699ed1f5ab0da562ca54c8e96ae6ed224f3d7daaee0f860ee95d1d8dd6"
    url = "https://github.com/JuliaBinaryWrappers/unpaper_jll.jl/releases/download/unpaper-v7.0.0+0/unpaper.v7.0.0.x86_64-linux-musl.tar.gz"
[[unpaper]]
arch = "x86_64"
git-tree-sha1 = "dc7e7a73b4a69e21fe688e012adf578e87212dac"
os = "freebsd"

    [[unpaper.download]]
    sha256 = "b6ce10948663e2ae7d7e8f1593f4faeca542ffc3c1d62d17277f4db336dac5a8"
    url = "https://github.com/JuliaBinaryWrappers/unpaper_jll.jl/releases/download/unpaper-v7.0.0+0/unpaper.v7.0.0.x86_64-unknown-freebsd.tar.gz"
[[unpaper]]
arch = "x86_64"
git-tree-sha1 = "a8ba574f4362ea0b52b9230a04b6dba4f48ac4d8"
os = "windows"

    [[unpaper.download]]
    sha256 = "bc18cf9bca94ea4c377b47e64b88939705e9a0e138b19a89ff1883b14effdbfc"
    url = "https://github.com/JuliaBinaryWrappers/unpaper_jll.jl/releases/download/unpaper-v7.0.0+0/unpaper.v7.0.0.x86_64-w64-mingw32.tar.gz"
