name = "unpaper_jll"
uuid = "d52248c9-e08a-51c2-9066-05d0bf3e6245"
version = "7.0.0+0"

[deps]
FFMPEG_jll = "b22a6f82-2f65-5046-a5b2-351ab43fb4e5"
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"

[compat]
JLLWrappers = "1.7.0"
julia = "1.6"
FFMPEG_jll = "8.0.1"
Libdl = "< 0.0.1, 1"
Artifacts = "< 0.0.1, 1"
